### ISSUE TITLE
New Bug found

### ISSUE THREAD

**Issue by TysonRanslow** [TysonRanslow/githubtracking#1]
Jill creates a bug and assigns to Willie.
    Willie rejects the bug as won't-fix back to Jill.
    Jill reactivates the bug again back to Willie.
    Willie assigns the bug to Mikey.
    Mikey fixes the bug and resolves it as fixed.
    Jill reactivates the bug again.
    Mikey finally fixes the bug (for real this time – Mikey is "Bob" in this team).
    Jill closes the bug.

**Comment by dylanJech** [comment]
Nah, I don't really feel like it

**Comment by TysonRanslow** [comment]
Please fix!

**Comment by J-Dill** [comment]
Nah, Mikey can do it.

**Comment by JohnTeeslink** [comment]
The bug is fixed, probably.

**Comment by TysonRanslow** [comment]
fix it this time

**Comment by JohnTeeslink** [comment]
Ok sure.  Its all good now. Trust me.

**Comment by TysonRanslow** [comment]
CLosed
